### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by zhasm** [layerssss/lixian-portal#28]
```
connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead ../../usr/lib/node_modules/lixian-portal/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:56:20
connect deprecated limit: Restrict request size at location of read ../../usr/lib/node_modules/lixian-portal/node_modules/express/node_modules/connect/lib/middleware/multipart.js:86:15
connect deprecated methodOverride: use method-override npm module instead ../../usr/lib/node_modules/lixian-portal/app.iced:54:19
刷新任务列表 启动
未登录
刷新任务列表 失败

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
  at errnoException (net.js:905:11)
  at Server._listen2 (net.js:1043:14)
  at listen (net.js:1065:10)
  at Server.listen (net.js:1139:5)
  at address (/usr/lib/node_modules/lixian-portal/app.iced:186:9)
  at /usr/lib/node_modules/lixian-portal/app.iced:187:3
  at Deferrals.runtime.Deferrals.Deferrals._call (/usr/lib/node_modules/lixian-portal/node_modules/iced-coffee-script/lib/coffee-script/iced.js:115:18)
  at /usr/lib/node_modules/lixian-portal/node_modules/iced-coffee-script/lib/coffee-script/iced.js:127:26
  at Object.runtime.trampoline (/usr/lib/node_modules/lixian-portal/node_modules/iced-coffee-script/lib/coffee-script/iced.js:94:16)
  at Deferrals.runtime.Deferrals.Deferrals._fulfill (/usr/lib/node_modules/lixian-portal/node_modules/iced-coffee-script/lib/coffee-script/iced.js:126:26)
  at ret (/usr/lib/node_modules/lixian-portal/node_modules/iced-coffee-script/lib/coffee-script/iced.js:65:20)
  at fs.js:272:14
  at Object.oncomplete (fs.js:108:15)
```

**Comment by layerssss** [comment]
这个提示应该是端口（网页服务器使用的端口）已被占用
