### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by houzy** [layerssss/lixian-portal#8]
安装完毕后，运行回报错：
portal ready on http://0.0.0.0:3000/
Command failed: Traceback (most recent call last):
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian_cli.py", line 63, in <module>
    execute_command()
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian_cli.py", line 60, in execute_command
    commands[command](args[1:])
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian_cli_parser.py", line 165, in parse
    return f(parser(args_list, _args, *_kwargs))
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian_commands/list.py", line 38, in list_task
    client = create_client(args)
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian_commands/util.py", line 53, in create_client
    return XunleiClient(args.username, args.password, args.cookies)
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian.py", line 58, in **init**
    self.login()
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian.py", line 184, in login
    raise NotImplementedError('user is not logged in')
NotImplementedError: user is not logged in
提示没有登录，我打开网页登录，一直没登上，终端有报错：
Command failed: Traceback (most recent call last):
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian_cli.py", line 63, in <module>
    execute_command()
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian_cli.py", line 60, in execute_command
    commands[command](args[1:])
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian_cli_parser.py", line 165, in parse
    return f(parser(args_list, _args, *_kwargs))
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian_commands/login.py", line 40, in login
    client = create_client(args)
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian_commands/util.py", line 53, in create_client
    return XunleiClient(args.username, args.password, args.cookies)
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian.py", line 58, in **init**
    self.login()
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian.py", line 191, in login
    assert verifycode
AssertionError
手动调用xunlei_lixian登录后，再运行lixian-portal，网页能打开，但是一直显示正在刷新任务列表，终端报错：
portal ready on http://0.0.0.0:3000/
Command failed: Traceback (most recent call last):
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian_cli.py", line 63, in <module>
    execute_command()
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian_cli.py", line 60, in execute_command
    commands[command](args[1:])
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian_cli_parser.py", line 165, in parse
    return f(parser(args_list, _args, *_kwargs))
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian_commands/list.py", line 47, in list_task
    tasks = lixian_query.search_tasks(client, args)
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian_query.py", line 398, in search_tasks
    base.query_search()
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian_query.py", line 153, in query_search
    self.download_jobs += query.query_search()
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian_query.py", line 347, in query_search
    return self.base.get_tasks()
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian_query.py", line 49, in get_tasks
    self.tasks = self.fetch_tasks()
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian.py", line 266, in read_all_tasks
    tasks, next_link = self.read_task_page(type_id)
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian.py", line 254, in read_task_page
    return self.read_task_page_url(url)
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian.py", line 222, in read_task_page_url
    data = parse_json_response(page)
  File "/usr/lib/node_modules/lixian-portal/xunlei-lixian/lixian.py", line 646, in parse_json_response
    raise RuntimeError('Invalid response')
RuntimeError: Invalid response
究竟咋回事？

**Comment by layerssss** [comment]
第二个错误是因为出现了验证码，第一个没提示登录和第三个待我下班后调查调查先

**Comment by layerssss** [comment]
我升级了 xunlei-lixian ，也改了一下安装方法（简化了），你在试一下吧

**Comment by houzy** [comment]
错误没了，好了，谢谢。
